version: '3.1'
# 定义网络
# 节点	IP
# Mysql	      192.168.1.100/24
# Mongodb	  192.168.1.101/24
# Redis	      192.168.1.102/24
# EMQX	      192.168.1.103/24
# EZLinker	  192.168.1.104/24
# Redis	      192.168.1.105/24
networks:
  ezlinker_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
# 定义服务
services:
  # Mysql
  mysql:
    # 使用最新版Mysql
    image: mysql
    container_name: "ezlinker_mysql"
    # 环境变量
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
    # 映射数据卷
    volumes:
      - ~/docker/mysql8/data:/var/lib/mysql
      - ~/docker/mysql8/log:/var/log/mysql
      - ~/docker/mysql8/mysql-files:/var/lib/mysql-files
    restart: always
    # 对外断口
    ports:
      - 53306:3306
      - 53060:33060
    # 启动后执行命令
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    # 日志限制
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    # 网络
    networks:
      ezlinker_net:
        ipv4_address: 192.168.1.100
  # Mongodb
  mongo:
    image: mongo
    container_name: ezlinker_mongo
    volumes:
      - ~/docker/mongodb/db:/data/db
      - ~/docker/mongodb/configdb/:/data/configdb
    ports:
      - "57017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ezlinker_mongo
    networks:
      ezlinker_net:
        ipv4_address: 192.168.1.101
  # Redis
  redis:
    image: redis
    container_name: ezlinker_redis
    command: redis-server --requirepass ezlinker_redis --appendonly yes
    ports:
      - "56379:6379"
    volumes:
      - ~/docker/redis/data:/data
    restart: always
    networks:
      ezlinker_net:
        ipv4_address: 192.168.1.102