# Server info
server:
  servlet:
    context-path: /ezlinker
  port: 2500
# Spring config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://112.74.44.130:3306/ezlinker?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=NO
      username: easylinker
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false


  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 300
    password: redis

  data:
    mongodb:
      uri: mongodb://localhost:27017
      # password: guest
      # username: guest
      port: 27017
      database: ezlinker
      authentication-database: admin
  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

aliyun:
  mail:
    access-key: ULw8nLnKBktSbOhI
    secret: hgAj2F2KtaMvLuXZzpVyVWZ0rl4SXR
    region-id: cn-hangzhou
    account-name: ezlinker@ezlinker.cn
    from-alias: EZLinker
    address-type: 1
    tag-name: EZLinker
